myapp/urls.py
from . import views
from django.urls import path
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', views.home, name='home'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('category/<str:category>/', views.category_products, name='category_products'),
    path('cart/', views.cart_view, name='cart_view'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('get_cart_details/', views.get_cart_details, name='get_cart_details'),
    path('checkout/', views.checkout, name='checkout'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('shop/', views.shop_view, name='shop'),
    path('contactus/', views.contactus, name='contactus'),
    path('check-authentication/', views.check_authentication, name='check_authentication'),
    path('remove-from-cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update_subtotal/', views.update_subtotal, name='update_subtotal'),
    path('logo_uniquefindertraders with background.ico', RedirectView.as_view(url='/static/images/logo_uniquefindertraders with background.ico')),


    # path('wishlist/add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    # path('wishlist/', views.wishlist_view, name='wishlist'),
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Product(models.Model):
    CATEGORY = (
        ('Baby', 'Baby'),
        ('DIY & Tools', 'DIY & Tools'),
        ('Grocery', 'Grocery'),
        ('Health & Beauty', 'Health & Beauty'),
        ('Home & Kitchen', 'Home & Kitchen'),
        ('Office Products', 'Office Products'),
        ('Pet Supplies', 'Pet Supplies'),
        ('Sports & Outdoors', 'Sports & Outdoors'),
        ('Toys', 'Toys'),
    )
    title = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    category = models.CharField(max_length=200, null=True, choices=CATEGORY)
    short_description = models.CharField(max_length=255, null=True, blank=True)
    detailed_description = models.TextField()

    def __str__(self):
        return self.title

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images/')

    def __str__(self):
        return f"Image for {self.product.title}"

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)

    def __str__(self):
        return f"Cart - User: {self.user.username}"

class BillingDetails(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    company_name = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=100, null=True)
    street_address = models.CharField(max_length=250, null=True)
    town_city = models.CharField(max_length=250, null=True)
    zip_code = models.CharField(max_length=250, null=True)
    phone = models.CharField(max_length=250, null=True)
    email = models.EmailField(max_length=254, null=True)
    order_notes = models.CharField(max_length=250, null=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)  # New field for subtotal


    def __str__(self):
        return f"BillingDetails - User: {self.user.username}"

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)
    order_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, default='Pending')
    billing_details = models.ForeignKey(BillingDetails, on_delete=models.CASCADE, null=True, blank=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

    def __str__(self):
        return f"Order #{self.id} - User: {self.user.username}, Status: {self.status}"
    
    # def total_price(self):
    #     # Calculate total price of all products in the order
    #     total = sum(product.price for product in self.products.all())
    #     return total

    # def __str__(self):
    #     return f"Order #{self.id} - User: {self.user.username}, Status: {self.status}"

# class Wishlist(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     products = models.ManyToManyField(Product)

#     def __str__(self):
#         return f"Wishlist for {self.user.username}"

myapp/forms.py
from django import forms

class BillingDetailsForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    company_name = forms.CharField(max_length=100, required=False)
    country = forms.CharField(max_length=100)
    street_address = forms.CharField(max_length=255)
    town_city = forms.CharField(max_length=100)
    zip_code = forms.CharField(max_length=20)
    phone = forms.CharField(max_length=20)
    email = forms.EmailField()
    order_notes = forms.CharField(widget=forms.Textarea, required=False)

myapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.http import JsonResponse, HttpResponse
from .forms import BillingDetailsForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

def home(request):
    products = Product.objects.all()
    products_baby = Product.objects.filter(category='Baby')[:4]  
    products_diy_tools = Product.objects.filter(category='DIY & Tools')[:4]  
    context = {
        'products': products,
        'products_baby': products_baby,
        'products_diy_tools': products_diy_tools,
    }
    return render(request, 'myapp/home.html', context)

def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product_images = ProductImage.objects.filter(product=product)
    category_products = Product.objects.filter(category=product.category)[:8]
    return render(request, 'myapp/product_detail.html', {'product': product, 'product_images': product_images, 'category_products': category_products})

def category_products(request, category):
    products = Product.objects.filter(category=category)
    return render(request, 'myapp/category_products.html', {'products': products})

def add_to_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    cart, _ = Cart.objects.get_or_create(user=request.user)
    cart.products.add(product)
    
    return redirect('cart_view')

def cart_view(request):
    if request.user.is_authenticated:
        cart, _ = Cart.objects.get_or_create(user=request.user)
        
        if cart:
            products_in_cart = cart.products.all()
            total_products_in_cart = products_in_cart.count()
            total_price = sum(product.price for product in products_in_cart)
        else:
            products_in_cart = []
            total_products_in_cart = 0
            total_price = 0

        return render(request, 'myapp/cart.html', {
            'products_in_cart': products_in_cart,
            'total_products_in_cart': total_products_in_cart,
            'total_price': total_price
        })
    else:
        return redirect('account_login')  # Redirect unauthenticated users to login page


def get_cart_details(request):
    # Logic to fetch total_products and total_price from the cart
    cart, _ = Cart.objects.get_or_create(user=request.user)
    
    if cart:
        products_in_cart = cart.products.all()
        total_products = products_in_cart.count()

        # Calculate total price
        total_price = sum(product.price for product in products_in_cart)
    else:
        total_products = 0
        total_price = 0

    data = {
        'total_products': total_products,
        'total_price': total_price,
    }
    return JsonResponse(data)

# def checkout(request):
#     if request.method == 'POST':
#         form = BillingDetailsForm(request.POST)
#         if form.is_valid():
#             order = Order.objects.create(
#                 user=request.user,
#                 # Assign form data to respective model fields
#                 first_name=form.cleaned_data['first_name'],
#                 last_name=form.cleaned_data['last_name'],
#                 # Add other form fields here
#             )
#             return render(request, 'myapp/checkout_success.html')
#     else:
#         form = BillingDetailsForm()
    
#     return render(request, 'myapp/checkout.html', {'form': form})

def checkout(request):
    if request.user.is_authenticated:
        cart, _ = Cart.objects.get_or_create(user=request.user)
        products_in_cart = cart.products.all()

        if products_in_cart.exists():
            current_order = Order.objects.filter(user=request.user).first()

            if current_order:
                total_price = current_order.total_price
            else:
                total_price = 0

            if request.method == 'POST':
                form = BillingDetailsForm(request.POST)
                if form.is_valid():
                    billing_details = BillingDetails.objects.create(
                        user=request.user,
                        first_name=form.cleaned_data['first_name'],
                        last_name=form.cleaned_data['last_name'],
                        company_name=form.cleaned_data['company_name'],
                        country=form.cleaned_data['country'],
                        street_address=form.cleaned_data['street_address'],
                        town_city=form.cleaned_data['town_city'],
                        zip_code=form.cleaned_data['zip_code'],
                        phone=form.cleaned_data['phone'],
                        email=form.cleaned_data['email'],
                        order_notes=form.cleaned_data['order_notes'],
                        # Add other form fields here
                    )
                    order = Order.objects.create(
                        user=request.user,
                        billing_details=billing_details,
                        # Add other order-related fields here
                        total_price=total_price  # Set the total_price from the current order
                    )

                    # Assuming you have a way to retrieve products (cart, session)
                    cart, _ = Cart.objects.get_or_create(user=request.user)
                    order.products.set(cart.products.all())

                    # Clear cart/session
                    cart.products.clear()
                    request.session['cart'] = []

                    return render_checkout_success(request, order)
                
            else:
                form = BillingDetailsForm()
            
            return render(request, 'myapp/checkout.html', {'form': form, 'total_price': total_price})
        else:
            # Handle the case where there are no products in the cart
            return HttpResponse("Go the home page")
    else:
        return redirect('account_login')  # Redirect unauthenticated users to login page

def render_checkout_success(request, order):
    products = order.products.all()
    return render(request, 'myapp/checkout_success.html', {'products': products})

def aboutus(request):
    return render(request, 'myapp/aboutus.html')

def shop_view(request):
    all_products = Product.objects.all()
    paginator = Paginator(all_products, 12)  # Show 12 products per page

    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver last page of results.
        products = paginator.page(paginator.num_pages)

    return render(request, 'myapp/shop.html', {'products': products})

def contactus(request):
    return render(request, 'myapp/contactus.html')

# def add_to_wishlist(request, product_id):
#     product = get_object_or_404(Product, pk=product_id)
#     Wishlist.objects.get_or_create(user=request.user, product=product)
#     return redirect('wishlist')

# def wishlist_view(request):
#     wishlist_items = Wishlist.objects.filter(user=request.user)
#     return render(request, 'myapp/wishlist.html', {'wishlist_items': wishlist_items})



def check_authentication(request):
    if request.user.is_authenticated:
        # User is authenticated
        return JsonResponse({'authenticated': True})
    else:
        # User is not authenticated
        return JsonResponse({'authenticated': False})

def remove_from_cart(request, product_id):
    if request.user.is_authenticated:
        cart, _ = Cart.objects.get_or_create(user=request.user)
        product = get_object_or_404(Product, pk=product_id)

        # Remove the product from the cart
        cart.products.remove(product)

        data = {'message': 'Product removed successfully'}
        return JsonResponse(data)
    else:
        data = {'error': 'User not authenticated'}
        return JsonResponse(data, status=401)

def update_subtotal(request):
    if request.method == 'POST':
        subtotal_value = request.POST.get('subtotal', '0.00')

        # Assuming you have a user associated with the request
        user = request.user

        # Get or create BillingDetails instance for the user
        billing_details, created = BillingDetails.objects.get_or_create(user=user)

        # Update subtotal and save
        billing_details.subtotal = subtotal_value
        billing_details.save()

        return JsonResponse({'status': 'success', 'subtotal': str(billing_details.subtotal)})
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'})

myapp/templates/myapp/cart.html
{% extends "myapp/main.html" %}
{% load static %}
{% block title %}Cart - UniqueFinderTrades{% endblock %}

{% block content %}

<div class="cart">
    <div class="shoppingcart mb-5">
        <a href="">
            SHOPPING CART
        </a>
    </div>
    {% if products_in_cart %}
    <div class="container">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-8">
                    <table class="carttable">
                        <thead>
                            <tr>
                                <th></th>
                                <th></th>
                                <th>Product</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Subtotal</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in products_in_cart %}
                            <tr id="cart-row-{{ product.id }}">
                                <td><i class="fa-solid fa-xmark" onclick="removeFromCart({{ product.id }})"></i></td>
                                <td class="wi__12">
                                    <a href="">
                                        {% if product.productimage_set.exists %}
                                        {% with product.productimage_set.first.image.url as first_image %}
                                        <img src="{{ first_image }}" alt="{{ product.title }}">
                                        {% endwith %}
                                        {% endif %}
                                    </a>
                                </td>
                                <td><a href="">{{ product.title }}</a></td>
                                <td class="product-price">${{ product.price }}</td>
                                <td>
                                    <div class="quantity">
                                        <button class="decrement">-</button>
                                        <input type="number" class="count" value="1" data-product-id="{{ product.id }}">
                                        <button class="increment">+</button>
                                    </div>
                                </td>
                                <td class="total-price">${{ product.price }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-lg-4">
                    <div class="card" id="subtotal-section">
                        <div class="card-body">
                            <h3 class="card-title">CART TOTALS</h3>
                            <hr>
                            <p class="card-text total__p">Total <span class="float-end" id="subtotal">$0.00</span></p>
                            <a class="cart__btn" href="{% url 'checkout' %}">PROCEED TO CHECKOUT</a>

                            <!-- Other content in the card -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="text-center cart__empty">
        <h1>
            Your cart is currently empty.
        </h1>
        <p>
            Before proceeding to checkout, you must add some products to your shopping cart.
            <br>
            You will find a lot of interesting products on our "Shop" page.

        </p>
        <div class="mt-4">
            <a class="productdetail__btn mt-4" href="{% url 'shop' %}">RETURN TO SHOP</a>
        </div>
    </div>
    {% endif %}
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var userIsAuthenticated = {% if request.user.is_authenticated %}true{% else %}false{% endif %};
        const decrementBtns = document.querySelectorAll('.decrement');
        const incrementBtns = document.querySelectorAll('.increment');
        const countInputs = document.querySelectorAll('.count');
        const productPrices = document.querySelectorAll('.product-price');
        const totalPrices = document.querySelectorAll('.total-price');
        const subtotalElement = document.getElementById('subtotal');

        // Function to update the total price based on quantity
        function updateTotalPrice(index) {
            const quantity = parseInt(countInputs[index].value);
            const price = parseFloat(productPrices[index].textContent.replace('$', ''));
            const totalPrice = quantity * price;
            totalPrices[index].textContent = '$' + totalPrice.toFixed(2);
            updateSubtotal(); // Update subtotal when the total price changes
            updateTotalPriceInHeader();
            const productId = countInputs[index].dataset.productId;
            // Update the hidden input value for quantity
            document.getElementById(`quantity_${productId}`).value = quantity;
        }

        // Add event listeners to increment and decrement buttons
        decrementBtns.forEach((btn, index) => {
            btn.addEventListener('click', function () {
                let count = parseInt(countInputs[index].value);
                if (count > 1) {
                    count--;
                    countInputs[index].value = count;
                    updateTotalPrice(index);
                }
            });
        });

        incrementBtns.forEach((btn, index) => {
            btn.addEventListener('click', function () {
                let count = parseInt(countInputs[index].value);
                count++;
                countInputs[index].value = count;
                updateTotalPrice(index);
            });
        });

        // Function to calculate the subtotal
        function updateSubtotal() {
            let subtotal = 0;
            totalPrices.forEach(price => {
                subtotal += parseFloat(price.textContent.replace('$', ''));
            });
            subtotalElement.textContent = '$' + subtotal.toFixed(2);
        }

        // Initial calculation of total prices and subtotal
        totalPrices.forEach((price, index) => {
            updateTotalPrice(index);
        });

        function updateTotalPriceInNavbar() {
            // Calculate the total price based on the subtotal in the cart
            const subtotal = parseFloat(subtotalElement.textContent.replace('$', ''));

            $.ajax({
                url: '/update_total_price/', // Change this to your actual endpoint
                method: 'POST',
                data: { subtotal: subtotal },
                success: function (data) {
                    $('#totalPrice').text(data.newTotal);
                }
            });
        }
    });
</script>

<script>
    function removeFromCart(productId) {
        var userIsAuthenticated = {% if request.user.is_authenticated %}true{% else %}false{% endif %};
        if (userIsAuthenticated) {
            // Get the CSRF token from the cookie
            var csrfToken = document.cookie.match(/csrftoken=([^;]+)/)[1];

            // Send an AJAX request to remove the product from the cart
            $.ajax({
                url: '/remove-from-cart/' + productId + '/',
                method: 'POST',
                headers: { 'X-CSRFToken': csrfToken },
                success: function (data) {
                    // Remove the corresponding row from the HTML
                    $('#cart-row-' + productId).remove();

                    // Update the total price in the header dynamically
                    updateTotalPriceInHeader();

                    window.location.href = window.location.href;
  

                },
                error: function (error) {
                    console.error('Error removing product from cart:', error.responseText);
                }
            });
        } else {
            console.error('User not authenticated');
        }
    }
</script>

{% endblock %}

myapp/templates/myapp/category_products.html
{% extends "myapp/main.html" %}
{% load static %}
{% block title %}Category Products - UniqueFinderTrades{% endblock %}

{% block content %}
   <div class="container">
    <div class="homeproducts">
        <div class="col-lg-12">
            <div class="row">
                {% for product in products %}
                <div class="col-lg-3 mt-5">
                    <a href="{% url 'product_detail' product.id %}">
                        <div class="pos__r">
                            {% if product.productimage_set.exists %}
                            {% with product.productimage_set.first.image.url as first_image %}
                            <img src="{{ first_image }}" class="card-img-top" alt="{{ product.title }}">
                            {% endwith %}
                            {% endif %} 
                            <h5 class="card-title">{{ product.title }}</h5>
                            <p class="card-text homeproducts__pfirst">Category: {{ product.get_category_display }}</p>
                            <p class="card-text homeproducts__psecond text-danger">Price: ${{ product.price }}</p>
                            <!-- <div class="wishlist">
                                <i class="fa-regular fa-heart"></i>
                            </div> -->
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
   </div>
{% endblock  %}

myapp/templates/myapp/checkout.html
{% extends "myapp/main.html" %}
{% load static %}
{% block title %}Checkout - UniqueFinderTrades{% endblock %}

{% block content %}
<div class="shoppingcart">
    <a href="">
        CHECKOUT
    </a>
</div>
{% if empty_cart %}

<div class="text-center cart__empty">
    <h1>
        Sorry
    </h1>
    <p>
        Checkout is not available whilst your cart is empty.
    </p>
    <div class="mt-4">
        <a class="productdetail__btn mt-4" href="">RETURN TO SHOP</a>
    </div>
</div>
{% else %}
<div class="container">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-lg-6">
                <h1>Billing Details</h1>
                <form method="post" class="contactus__form" id="billing-form">
                    {% csrf_token %}
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-6">
                                <label for="id_first_name">First Name:</label>
                                <input type="text" id="id_first_name" name="first_name" maxlength="100" required><br>
                            </div>
                            <div class="col-lg-6">
                                <label for="id_last_name">Last Name:</label>
                                <input type="text" id="id_last_name" name="last_name" maxlength="100" required><br>
                            </div>
                        </div>
                    </div>

                    <label for="id_company_name">Company Name:(Optional)</label>
                    <input type="text" id="id_company_name" name="company_name" maxlength="100"><br>

                    <label for="id_country">Country:</label>
                    <input type="text" id="id_country" name="country" maxlength="100" required><br>

                    <label for="id_street_address">Street Address:</label>
                    <input type="text" id="id_street_address" name="street_address" maxlength="255" required><br>

                    <label for="id_town_city">Town/City:</label>
                    <input type="text" id="id_town_city" name="town_city" maxlength="100" required><br>

                    <label for="id_zip_code">Zip Code:</label>
                    <input type="text" id="id_zip_code" name="zip_code" maxlength="20" required><br>

                    <label for="id_phone">Phone:</label>
                    <input type="text" id="id_phone" name="phone" maxlength="20" required><br>

                    <label for="id_email">Email:</label>
                    <input type="email" id="id_email" name="email" required><br>

                    <label for="id_order_notes">Order Notes:(Optional)</label>
                    <textarea id="id_order_notes" name="order_notes"></textarea><br>

                    <button class="productdetail__btn" type="submit">Place Order</button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

myapp/templates/myapp/checkout_success.html
{% extends "myapp/main.html" %}
{% load static %}

{% block content %}

<div class="shoppingcart">
    <a href="">
        ORDER COMPLETE
    </a>
</div>
<div class="checksuccess">
    <div class="container">
        <div class="text-center">
            <h1>Checkout Success</h1>
            <p>Your order has been placed!</p>
        </div>
        <h2>Order Details:</h2>
        <table class="carttable">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td class="wi__12">
                        <a href="">
                            {% if product.productimage_set.exists %}
                            {% with product.productimage_set.first.image.url as first_image %}
                            <img src="{{ first_image }}" alt="{{ product.title }}">
                            {% endwith %}
                            {% endif %}
                        </a>
                    </td>
                    <td>{{ product.title }} <span>Quantity</span></td>
                    <td>{{ product.price }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>    
    </div>
</div>


{% endblock %}

myapp/templates/myapp/shop.html
{% extends "myapp/main.html" %}
{% load static %}
{% block title %}Shop{% endblock %}

{% block content %}

<div class="container">
    <h1 class="text-center">Shop</h1>

    <div class="homeproducts">
        <div class="col-lg-12">
            <div class="row">
                {% for product in products %}
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs- mt-5">
                    <a href="{% url 'product_detail' product.id %}">
                        <div class="pos__r">
                            {% if product.productimage_set.exists %}
                            {% with product.productimage_set.first.image.url as first_image %}
                            <img src="{{ first_image }}" class="card-img-top" alt="{{ product.title }}">
                            {% endwith %}
                            {% endif %}
                            <h5 class="card-title">{{ product.title }}</h5>
                            <p class="card-text homeproducts__pfirst">Category: {{ product.get_category_display }}</p>
                            <p class="card-text homeproducts__psecond text-danger">Price: ${{ product.price }}</p>
                            <!-- <div class="wishlist">
                                <i class="fa-regular fa-heart"></i>
                            </div> -->
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Pagination links -->
    <div class="pagination mt-3">
        <span class="step-links">
            {% if products.has_previous %}
                <a class="ms-2" href="?page=1">&laquo; first</a>
                <a class="ms-2" href="?page={{ products.previous_page_number }}">previous</a>
            {% endif %}

            {% for i in products.paginator.page_range %}
                {% if products.number == i %}
                    <span class="current me-2">
                        {{ i }}
                    </span>
                {% elif i > products.number|add:'-3' and i < products.number|add:'3' %}
                    <a class="ms-2" href="?page={{ i }}">{{ i }}</a>
                {% elif i == products.number|add:'3' or i == products.number|add:'-3' %}
                    ...
                {% endif %}
            {% endfor %}

            {% if products.has_next %}
                <a class="ms-2" href="?page={{ products.next_page_number }}">next</a>
                <a class="ms-2" href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock %}

myapp/templates/myapp/wishlist.html
{% extends "myapp/main.html" %}
{% load static %}

{% block content %}

{% for item in wishlist_items.products.all %}
    <!-- Display each wishlist item here -->
    <p>{{ item.title }}</p>
    <!-- Add other details as needed -->
{% empty %}
    <p>No items in the wishlist</p>
{% endfor %}

    <p>Your wishlist is empty.</p>
{% endblock %}